### ISSUE TITLE
Chargement permanent

### ISSUE THREAD

**Issue by ricotte38** [grenagit/MMM-VigilancePollensFrance#1]
Bonjour,

Depuis plusieurs semaines le module reste en chargement permanent affichant :  `Chargement...`
Par contre  [MMM-VigilanceMeteoFrance](https://github.com/grenagit/MMM-VigilanceMeteoFrance) fonctionne parfaitement, avez vous une idée ? Un problème d'api ?

Merci bien

**Comment by grenagit** [comment]
Bonjour @ricotte38,

Pas de problème de mon côté : le module se charge correctement et l'API à l'air opérationnelle...
Quelles est la configuration utilisée pour le module `MMM-VigilancePollensFrance` dans le fichier `config.js` (un petit copier/coller en commentaire) ?

Merci 😉

**Comment by ricotte38** [comment]
Bonjour,

Merci pour ton retour, ci dessous le code utilisé.
J'ai tenté une mise à jour et une réinstalle complète du module.

Merci de ton aide.

```js
{
	module: "MMM-VigilancePollensFrance",
	header: "Vigilance Pollens Grenoble",
	position: "top_left",
	config: {
		department: 38, // Department number
		showDepartment: true,
		showDescription: true,
		showNotification: false,
	}
},
```

**Comment by grenagit** [comment]
Le problème est **résolu** avec 03477d131b1347e0135fbbd1174ed49cd688f2a3 et la dernière version 🎉
> Il s'agissait d'un faux positif dans la détection de données corrompues en provenance de l'API.

Pour mettre à jour le module :
```sh
cd ~/MagicMirror/modules/MMM-VigilancePollensFrance
git pull
npm install
```

Merci @ricotte38 d'avoir signalé le problème 👍
