### ISSUE TITLE
Chargement permanent malgré mise à jour 0.1.1

### ISSUE THREAD

**Issue by ricotte38** [grenagit/MMM-VigilancePollensFrance#2]
Bonsoir,

Merci pour cette mise à jour, mais malheureusement je reste en "chargement..."

J'ai désinstallé puis réinstallé mais rien n'y fait. Je n'arrive pas à savoir ce qui se passe. peut être un conflit avec ma config?

S il y a une solution, 

Merci D'avance

**Comment by grenagit** [comment]
Le `showDescription: true,` ne sert à rien pour ce module mais cela ne vient pas de là...

*Avec :*
```js
		{
			module: "MMM-VigilancePollensFrance",
			header: "Vigilance Pollens Grenoble",
			position: "top_left",
			config: {
				department: 38, // Department number
				showDepartment: true,
				showNotification: false,
			}
		},
```
*J'ai :*
![MMM-VigilancePollensFrance](https://user-images.githubusercontent.com/46225780/148442751-92d7aff3-284b-4fdb-909e-6b10989d456c.png)

*Quelques pistes :*
- Le MagicMirror a-t-il bien été redémarré après la mise à jour ?
- Arrives-tu à accéder aux données à l'adresse https://www.pollens.fr/risks/thea/counties/38 ?
- As-tu un message d'erreur concernant **MMM-VigilancePollensFrance** dans la console (lancer le MagicMirror en mode développeur avec `cd MagicMirror/ && npm run start:dev`) ?

**Comment by ricotte38** [comment]
Oui la mise à jour a été terminé et j'ai redémarré plusieurs fois depuis, (j'avais déjà cela avant la dernière mise à jour).

J'accède à cela via le lien depuis le raspberry : 
```
{"countyName":"Is\u00e8re","countyNumber":"38","risks":[{"pollenName":"Tilleul","level":0},{"pollenName":"Ambroisies","level":0},{"pollenName":"Olivier","level":0},{"pollenName":"Plantain","level":0},{"pollenName":"Noisetier","level":0},{"pollenName":"Aulne","level":0},{"pollenName":"Armoise","level":0},{"pollenName":"Ch\u00e2taignier","level":0},{"pollenName":"Urticac\u00e9es","level":0},{"pollenName":"Oseille","level":0},{"pollenName":"Gramin\u00e9es","level":0},{"pollenName":"Ch\u00eane","level":0},{"pollenName":"Platane","level":0},{"pollenName":"Bouleau","level":0},{"pollenName":"Charme","level":0},{"pollenName":"Peuplier","level":0},{"pollenName":"Fr\u00eane","level":0},{"pollenName":"Saule","level":0},{"pollenName":"Cupressac\u00e9es","level":0}],"riskLevel":0}
```

Par contre j'ai ce message en DEV (cf piece jointe) : c'est comme il ne trouvait pas l'info...

Pourtant  au chargement :
```
Connecting socket for: MMM-VigilanceMeteoFrance
[06.01.2022 21:23.16.744] [LOG]   Starting module helper: MMM-VigilanceMeteoFrance
[06.01.2022 21:23.16.745] [LOG]   Connecting socket for: MMM-VigilancePollensFrance
[06.01.2022 21:23.16.746] [LOG]   Starting module helper: MMM-VigilancePollensFrance
[06.01.2022 21:23.16.746] [LOG]   Sockets connected & modules started ...
 ```

**Comment by ricotte38** [comment]
![Capture](https://user-images.githubusercontent.com/63130632/148447881-15c649bd-a364-4b60-b8ae-f25998f4c590.JPG)

**Comment by ricotte38** [comment]
![Capture](https://user-images.githubusercontent.com/63130632/148448378-783340da-70ed-452c-92d5-7c51680fb2bb.JPG)

**Comment by chassain** [comment]
Bonsoir, même symptôme chez moi

cdt

**Comment by grenagit** [comment]
Je pense avoir trouvé l'origine du problème... Mon cerveau ne devait pas être dans le bon sens quand j'ai corrigé le problème signalé par @ricotte38 🙃

Après une mise à jour le problème devrait être résolu
```sh
cd ~/MagicMirror/modules/MMM-VigilancePollensFrance
git pull
npm install
```
@ricotte38 et @chassain, j'attends votre retour avant de clôturer !

**Comment by ricotte38** [comment]
Hello
Parfait pour moi! au top....c’était quoi le problème finalement ?

Merci beaucoup

**Comment by chassain** [comment]
hidegreen à hidewhite...Merci pour la correction. :)

**Comment by chassain** [comment]
![Capture d’écran de 2022-01-07 22-49-52](https://user-images.githubusercontent.com/32990929/148612012-b018aade-98f6-4bfb-bedc-ca088d12917f.png)

**Comment by grenagit** [comment]
> Hello Parfait pour moi ! Au top... C’était quoi le problème finalement ?

En fait, le test de validité du niveau de risque retournait un `true` quand tout allait bien alors qu'il fallait un `false` 🙃

> hidegreen à hidewhite... Merci pour la correction. :)

Oui, j'ai en profité pour activer proprement la fonctionnalité 😉
